spring:
  application:
    name: eureka-server
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5433/customer
    username: amigoscode
server:
  port: 8761


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false